### PR TITLE
Add support for shared mode

### PR DESCRIPTION
**Pull request by lincsoon**
Add extra plugin to get the event from the activity and handle the
initialization by XWalkActivityDelegate which provided by the
infrastructure.

### CODE REVIEW

**Comment by lincsoon** [comment]
@fujunwei Please help to review

**Comment by lincsoon** [comment]
The infrastructure needed by this commit has been merged into the master branch of Crosswalk

**Comment by fujunwei** [comment]
LGTM, thanks.

**Comment by lincsoon** [comment]
@fujunwei Since the infrastructure has been prepared, please merge this pull request.

**Comment by huningxin** [comment]
LGTM! Merging.

**Pull request merged**
