### PR TITLE
[iOS] Added iOS platform support

### PR DESCRIPTION
**Pull request by jondong**
This is the first step by introducing Crosswalk Project for iOS into the Cordova plugin of Crosswalk WebView. When this feature completes this plugin will have iOS platform support with a enhanced WKWebView based XWalkView.

### CODE REVIEW

**Comment by jondong** [comment]
@fujunwei PTAL, thanks.

**Comment by fujunwei** [comment]
Please refine indent  in js file. Other LGTM

**Comment by jondong** [comment]
@fujunwei Thanks for the review, updated, PTAL

**Comment by fujunwei** [comment]
@huningxin @rakuco  @baleboy Do you have any comments

**Comment by rakuco** [comment]
not really, I do not have any experience with iOS development.

**Comment by halton** [comment]
@fujunwei  Are you asking the purpose of this PR?

If so, this feature is requested by customer, @baleboy is in the loop.

**Comment by fujunwei** [comment]
Crosswalk-16 will be released, which version it will be supported

**Comment by jondong** [comment]
@fujunwei I think we are targeting Crosswalk 17, as 16 should has been released by schedule.

**Comment by fujunwei** [comment]
Ok, It will be merged after release Crosswalk-16 if there are no updated comments.

**Comment by watf** [comment]
Cool.
¿When for Windows Phone 8?
I think it would be really appreciated, since there the render is Trident.. Nothing we can do with that..

**Comment by watf** [comment]
I also think that Microsoft is —slowly— going in the right way, winning more market.

But there's not one single webkit app nor browser. Makes me wanna throw up.
Please, at least a date, o an alpha version, anything.

**Comment by fujunwei** [comment]
Merging to master branch.

**Comment by dpogue** [comment]
Is this going to be a major version bump of the plugin?

I'm concerned about the breaking change for cross-platform projects that expect this plugin to only affect Android. What happens to user data (localStorage, WebSQL, IndexedDB) that's already stored in UIWebView or WKWebView? Will it seamlessly migrate to the new XWalkView?
How will this affect projects already using the core WKWebView plugin on iOS?

**Comment by jondong** [comment]
@dpogue Thanks for paying attention to this feature, that's good question. One of the intention to add iOS support is to provide the same Crosswalk API implementation across platform, although we still have a way to go. XWalkView derives from WKWebView with an embedding http server to solve the iOS 8 file loading issue, it it supposed to work pretty much the same as WKWebView iOS plugin written by Telerik, and the difference between the two is Crosswalk plugin for iOS targeting cordova-ios 4.0.0 above and leverage the new webview abstraction layer provided by Cordova, so this feature will only support Cordova iOS above v4.0.0. Meanwhile, if you installed WKWebView iOS plugin together with the Crosswalk WebView plugin with iOS support, as WKWebView iOS plugin hijacked the AppDelegate and use the method swizzling to replace the webview before the plugin get loaded, the Crosswalk WebView won't take effect in this case.

I'm not quite sure about the user data migration, by my guess if you've already adopted WKWebView plugin in your apps, the use data could be kept; but if you still use UIWebView then it won't.

**Comment by shazron** [comment]
"derives from WKWebView with an embedding http server" --> don't forget that to keep your localStorage/web storage persistent, the port for the http server has to be the same on each load https://github.com/apache/cordova-plugins/tree/master/local-webserver#localstorage-indexeddb-persistence

**Pull request merged**
