### PR TITLE
Do not show "Ssl Certificate error Alert" on bad SSL certificate

### PR DESCRIPTION
**Pull request by alexkvak**
According to https://github.com/infil00p/cordova-crosswalk-engine/issues/18

### CODE REVIEW

**Comment by alexkvak** [comment]
up

**Comment by fujunwei** [comment]
The commit has conflicts that need be resolved and could you please add  description of the function .

+    /**
+    * Notify the host application that an SSL error occurred while loading a
+    * resource. The host application must call either callback.onReceiveValue(true)
+    * or callback.onReceiveValue(false). Note that the decision may be
+    * retained for use in response to future SSL errors. The default behavior
+    * is to pop up a dialog.
+    */

**Comment by alexkvak** [comment]
Comment added

**Comment by fujunwei** [comment]
Could you please upgrade latest code to fix the conflicts so we can merge the PR. and it's better to squash the https://github.com/megaplan/cordova-plugin-crosswalk-webview/commit/2fe843827be0d7352926ed466392e4fef65c9558 to https://github.com/megaplan/cordova-plugin-crosswalk-webview/commit/e197cd5908315e188e4d4c887e945696aad685ee.

**Comment by alexkvak** [comment]
done

**Comment by fujunwei** [comment]
Thanks, LGTM.

**Pull request merged**
