### PR TITLE
Revert "[iOS] Enabled XWalkView within Cordova Crosswalk Plugin."

### PR DESCRIPTION
**Pull request by jondong**
Reverts crosswalk-project/cordova-plugin-crosswalk-webview#81

As discussed within crosswalk-dev and github community, we decide to remove the iOS support from this cordova plugin, and as Crosswalk iOS XWalkView does not provide any more must have features comparing with WKWebView, we are not going to implement a stand alone cordova plugin for it until we'll find a good reason to do this.

### CODE REVIEW

**Comment by jondong** [comment]
@fujunwei pleas help to merge, thanks.

**Comment by fujunwei** [comment]
https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/commit/c6a42d9cc046ab6b87e7b8a2da9f186b4a158cbc and https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/commit/e1976b37f3539ac2aa2a0625be7d63bf148388a0 also need to be removed?

**Comment by jondong** [comment]
yes it is suppose so. I will do it after this one get merged, thanks.

**Comment by fujunwei** [comment]
How about revert those commits in a PR?

**Comment by jondong** [comment]
fine, will do

**Comment by jondong** [comment]
Close this one and revert all the iOS related patches in another PR.

**Comment by kenvunz** [comment]
hi @jondong 
so is there anyway that i can embed the Crosswalk iOS engine to my Cordova hybrid app?

PS. sorry, i've been hopping around sites and don't really know where to ask this question. It's all has changed last time I checked especially the decision not to have official cordova plugin

**Pull request closed without merging**
