### PR TITLE
Build 64-bit apks

### PR DESCRIPTION
**Pull request by fujunwei**
Customer can use "cordova build android --xwalk64bit" to generate 64bit apks.

BUG=XWALK-6085 XWALK-5218

### CODE REVIEW

**Comment by baleboy** [comment]
Can this be configured from config.xml as well?

**Comment by fujunwei** [comment]
This option is used at build time, so it's not necessary to configure it in config.xml.

**Comment by confused-pv** [comment]
I am getting following error while building the apk

import org.xwalk.core.XWalkGetBitmapCallback;
                     ^
  symbol:   class XWalkGetBitmapCallback
  location: package org.xwalk.core
platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:103: error: cannot find symbol
                                    new XWalkGetBitmapCallback() {
                                        ^
  symbol: class XWalkGetBitmapCallback
platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java:207: error: cannot find symbol
            webView.getExtensionManager().loadExtension(XWALK_EXTENSIONS_FOLDER + File.separator + path);
                   ^
  symbol:   method getExtensionManager()
  location: variable webView of type XWalkCordovaView
platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java:93: error: method does not override or implement a method from a supertype
    @Override

**Comment by fujunwei** [comment]
The master branch of crosswalk plugin is based on crosswalk-18 that is canary version.you need to get it from https://download.01.org/crosswalk/releases/crosswalk/android/canary/18.46.471.0/crosswalk-18.46.471.0.aar, and then install it in local maven.

There are three steps:
1, install downloaded AAR file
```
mvn install:install-file -DgroupId=org.xwalk -DartifactId=xwalk_core_library_canary \
      -Dversion=18.46.471.0 -Dpackaging=aar  -Dfile=crosswalk-18.46.471.0.aar \
      -DgeneratePom=true
```

2, Modify root/config.xml to use the canary AAR
```
<preference name="xwalkVersion" value="org.xwalk:xwalk_core_library_canary:18.46.470.0" />
```

3, Add mavenLocal() to platfrom/android/cordova-plugin-crosswalk-webview/**-xwalk.gradle file
```
repositories {
  maven {
    url 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2'
  }
  mavenLocal()
}
```

**Pull request merged**
