### PR TITLE
Bump version to 2.2.0

### PR DESCRIPTION
**Pull request by fujunwei**

### CODE REVIEW

**Comment by dpogue** [comment]
Might want to note that this version requires cordova-android 6.0.0 or newer

**Comment by baleboy** [comment]
@dpogue I thought PR #101 had made it compatible with 5.x as well.

**Comment by dpogue** [comment]
No, that just enforces that version <=2.1.0 of this plugin is only compatible with cordova-android 4.x and 5.x, and version 2.2.0 is only compatible with cordova-android 6.x

**Comment by baleboy** [comment]
@dpogue I see now, thanks.

**Comment by mdw7326** [comment]
@fujunwei I need to post an issue on this repository but you do not have issues enabled. Commenting on a PR is the only way I can contact any contributor currently. Can you email me at mdw7326@rit.edu to discuss solutions?

**Comment by fujunwei** [comment]
@dpogue Thanks, Done.

**Comment by fujunwei** [comment]
You can file a issue on JIRA https://crosswalk-project.org/jira

**Comment by pke** [comment]
Uhmm guys, when you increase a major dependency shouldn't u also update the major version of this plugin?
Since `2.1.0` guaranteed to work against `cordova-android 5.1.1` one could specify `^2.1.0` in `config.xml`. That, imho, allowed updates to `cordova-android 5.x.x` but not `6.x.x`. Today my app broke because of that.
Now `2.2.0` updates a peer-dependency, got updated when I re-added the platform during CI run and it broke the build. For a minor version increase that is not allowed to happen, according to semver, isnt't it?

**Comment by fujunwei** [comment]
2.2.0 updates cordova-android 5.x.x to 6.x.x in order to keep compatibility for the version of cordova-android, not for cordova CLI version, so i don't think it's necessary to update plugin version to 3.0.0

**Comment by fujunwei** [comment]
And 2.2.0 means that the plugin is using Crosswalk-22 stable version. it's easy to understand.

**Comment by pke** [comment]
@fujunwei 
> 2.2.0 updates cordova-android 5.x.x to 6.x.x in order to keep compatibility for the version of cordova-android, not for cordova CLI version

I don't get what u are saying here. Nobody talked about CLI.

Also why tie this plugin version to some other things version? If any it should then be 22.x.x already, shouldn't it?

The fact remains, this minor version change breaks the plugin, because it updated a dependency that was stable before. You can't do that when using semver.

**Comment by pke** [comment]
> And 2.2.0 means that the plugin is using Crosswalk-22 stable version. it's easy to understand.

Hmm. But 1.8.0 was using Crosswalk-19 stable version. So it should have been 1.9.0?
And  1.7.0 was using Crosswalk-18 by default. Confusing. Not easy to understand at all.
https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/commit/ac2ef0d953dde45acf9e83f1ce5efd056d91322c

**Comment by baleboy** [comment]
@pke there is no relation between the plugin version and the Crosswalk version, 1.9 = 19 is just a coincidence. Plugin releases can happen for other reasons than a Crosswalk update, e.g. add a configuration parameter, align with latest Cordova etc.

**Comment by pke** [comment]
@baleboy 
> there is no relation between the plugin version and the Crosswalk version, 1.9 = 19 is just a coincidence.

Exactly! All I did was to contradict @fujunwei when he wrote:
> And 2.2.0 means that the plugin is using Crosswalk-22 stable version. it's easy to understand.

So get the versioning fixed here please. The current way this plugin handles versioning is harmful to `^` semver specs.

**Comment by fujunwei** [comment]
> Hmm. But 1.8.0 was using Crosswalk-19 stable version. So it should have been 1.9.0?
And 1.7.0 was using Crosswalk-18 by default. Confusing. Not easy to understand at all.
You are right, It's corrected from 2.0.0

**Comment by reidab** [comment]
Any chance of merging this in since 2.2.0 is already on npm? I had a few hours of confusion because I saw this open PR and assumed 2.2.0 was still awaiting release. It would be nice to have the changelog and package version here in master be up to date with what's on NPM.

**Pull request merged**
