### PR TITLE
Fixes streching of view on keyboard open

### PR DESCRIPTION
**Pull request by Nielsb85**
Fixes stretching of view on keyboard open in Android (Lollipop)

https://crosswalk-project.org/jira/browse/XWALK-3547?focusedCommentId=33278&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-33278

### CODE REVIEW

**Comment by axinging** [comment]
@fujunwei

**Comment by chuckmitchell** [comment]
This fixed the issue in our app and made it possible to move forward with crosswalk. 
I'll be forking the project until this gets straightened out. 
Thank you for the fix!

**Comment by agrieve** [comment]
The intention was that Animatable would be false by default. If that's not what's happening, then how about taking out the "if" and adding in:

    XWalkPreferences.setValue(XWalkPreferences.ANIMATABLE_XWALK_VIEW, prefAnimatable || manifestAnimatable);

**Comment by chuckmitchell** [comment]
@axinging @fujunwei

I was looking at the docs for CrosswalkAnimatable, I was wondering why CrosswalkAnimatable, true is important as the default for cordova-plugin-crosswalk-webview. I see the default for XWalkPreferences is false but this has been changed in the plugin, and that the docs mention there are performance advantages using SurfaceView over TextureView which exposes this bug. 

Would it be possible to add an option in cordova's config.xml for dev's to choose their preference?

Cheers,
Charles Mitchell

https://crosswalk-project.org/apis/embeddingapidocs/reference/org/xwalk/core/XWalkPreferences.html#ANIMATABLE_XWALK_VIEW

**Comment by zarko-tg** [comment]
I wonder who and which party owns the resolution of this issue. It's a big usability problem when interacting with input fields. From what I can see there's no indication that the reasons for the faulty behaviour are fully understood.
Cordova, Crosswalk, Android?

**Comment by jacargentina** [comment]
Yeah, this would fix my ionic framework app on Android 5

**Comment by fujunwei** [comment]
It have been implemented in https://github.com/crosswalk-project/crosswalk/pull/3089.

**Comment by jonathanewerner** [comment]
any information when this will land in a release? thanks for your work!

**Comment by fujunwei** [comment]
Duplicate with https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/commit/f82d5e41eb438cd810494d8511eae5006d82c1f9 that have merged into master, so close it.

**Pull request closed without merging**
